# Generated by Django 4.1.7 on 2024-02-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0038_dtcmanifesto_manifesto_dtcmanifesto_manifesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesto',
            name='dtc',
            field=models.ManyToManyField(through='operacional.DtcManifesto', to='operacional.dtc'),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='motoristas',
            field=models.ManyToManyField(to='operacional.motorista'),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='veiculos',
            field=models.ManyToManyField(to='operacional.veiculo'),
        ),
    ]
