# Generated by Django 4.1.7 on 2024-03-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0039_alter_manifesto_dtc_alter_manifesto_motoristas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissor',
            name='aliquota',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='emissor',
            name='sigla_filial',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
