# Generated by Django 4.1.7 on 2024-03-20 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0040_emissor_aliquota_emissor_sigla_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesto',
            name='ocorrencia_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operacional.ocorrencia_manifesto'),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='dtc',
            field=models.ManyToManyField(to='operacional.dtc'),
        ),
    ]
