# Generated by Django 5.0.6 on 2024-07-20 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0001_initial'),
        ('operacional', '0049_alter_rota_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cte',
            name='faturas_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cte_faturas', to='faturamento.faturas'),
        ),
    ]
