# Generated by Django 5.1.1 on 2024-10-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0050_cte_faturas_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cte',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
