# Generated by Django 5.1.1 on 2024-10-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0051_alter_cte_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='data_da_coleta',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cte',
            name='data_entrega',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cte',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
