# Generated by Django 5.1.1 on 2024-10-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0052_coleta_data_da_coleta_cte_data_entrega_cte_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='coleta',
            name='lng',
            field=models.DecimalField(decimal_places=8, max_digits=9, null=True),
        ),
    ]
