# Generated by Django 5.1.1 on 2025-01-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0053_coleta_lat_coleta_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleta',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
