# Generated by Django 5.1.1 on 2025-01-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0054_alter_coleta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleta',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
