# Generated by Django 5.1.1 on 2025-01-07 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0055_alter_coleta_lat_alter_coleta_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Ocorrência',
                'verbose_name_plural': 'Categorias de Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_ocorrencias', to='operacional.categoriaocorrencia')),
            ],
            options={
                'verbose_name': 'Tipo de Ocorrência',
                'verbose_name_plural': 'Tipos de Ocorrências',
                'ordering': ['categoria', 'codigo'],
            },
        ),
    ]
