# Generated by Django 5.1.1 on 2025-01-07 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0056_categoriaocorrencia_tipoocorrencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ocorrencia', models.DateTimeField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('coleta_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_coleta_fk', to='operacional.coleta')),
                ('cte_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_cte_fk', to='operacional.cte')),
                ('dtc_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_dtc_fk', to='operacional.cte')),
                ('tipo_ocorrencia_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_tipo_ocorrencia_fk', to='operacional.tipoocorrencia')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['data_ocorrencia'],
            },
        ),
    ]
