# Generated by Django 5.1.1 on 2025-01-07 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0057_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='manifesto_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_dtc_fk', to='operacional.manifesto'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='dtc_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_dtc_fk', to='operacional.dtc'),
        ),
    ]
