# Generated by Django 5.1.1 on 2025-01-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0058_ocorrencia_manifesto_fk_alter_ocorrencia_dtc_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoocorrencia',
            name='finalizadora',
            field=models.BooleanField(default=False, help_text='Indica se a ocorrência finaliza o processo do Cte ou da Coleta.'),
        ),
    ]
