# Generated by Django 5.1.1 on 2025-01-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0059_tipoocorrencia_finalizadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='hora_ocorrencia',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='hora_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_ocorrencia',
            field=models.DateTimeField(null=True),
        ),
    ]
