# Generated by Django 5.1.1 on 2025-01-10 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0060_ocorrencia_hora_ocorrencia_ocorrencia_hora_registro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='usuario_cadastro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastrado_ocorrencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='hora_ocorrencia',
            field=models.CharField(default='00:00', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='hora_registro',
            field=models.CharField(default='00:00', max_length=10, null=True),
        ),
    ]
