# Generated by Django 5.1.1 on 2025-07-09 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0062_coleta_usuario_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_fiscal',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='dtc_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='operacional.dtc'),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='especie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='m3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='natureza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='peso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='valor_nf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='volume',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
