# Generated by Django 5.1.1 on 2025-02-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
                ('fone_email_etc', models.CharField(max_length=50, unique=True)),
                ('estado_conversa', models.JSONField(default=dict)),
            ],
        ),
    ]
