# Generated by Django 5.1.1 on 2025-02-18 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('estado_conversa', models.JSONField(default=dict)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='chatbot.estadoconversa')),
            ],
            options={
                'ordering': ['data_envio'],
            },
        ),
    ]
