# Generated by Django 5.1.1 on 2025-02-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoconversa',
            name='descricao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estadoconversa',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
