# Generated by Django 5.1.1 on 2024-10-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_municipios'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecos',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='enderecos',
            name='lng',
            field=models.DecimalField(decimal_places=8, max_digits=9, null=True),
        ),
    ]
