# Generated by Django 5.1.1 on 2024-10-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0004_enderecos_lat_enderecos_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecos',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
