# Generated by Django 5.1.1 on 2025-07-09 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0005_alter_enderecos_lat_alter_enderecos_lng'),
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilialResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial_responsavel', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('parceiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filiais_responsaveis', to='parceiros.parceiros')),
            ],
        ),
    ]
