# Generated by Django 5.1.1 on 2025-07-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0006_filialresponsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filialresponsavel',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='filialresponsavel',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='filialresponsavel',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='filialresponsavel',
            name='uf',
        ),
    ]
