# Generated by Django 4.0.6 on 2022-09-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelafrete',
            name='freteMinimo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
