# Generated by Django 4.0.6 on 2022-09-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_tabelafrete_freteminimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelafrete',
            name='tipoTabela',
            field=models.IntegerField(default=1),
        ),
    ]
