# Generated by Django 4.0.6 on 2022-10-19 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_tabelafrete_tipotabela'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixaInicial', models.IntegerField()),
                ('faixaFinal', models.IntegerField()),
                ('vlrFaixa', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('tblVinculada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.tabelafrete')),
            ],
        ),
    ]
