# Generated by Django 4.0.6 on 2022-10-20 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_tabelafaixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelafaixa',
            name='tblVinculada',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.tabelafrete'),
        ),
    ]
