# Generated by Django 5.0.6 on 2024-07-20 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacional', '0049_alter_rota_nome'),
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fatura', models.CharField(max_length=20, unique=True)),
                ('data_emissao', models.DateField()),
                ('vencimento', models.DateField()),
                ('valor_total', models.FloatField()),
                ('valor_a_pagar', models.FloatField()),
                ('desconto', models.FloatField(default=0.0)),
                ('impostos', models.FloatField(default=0.0)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('emissor_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faturaEmissor', to='operacional.emissor')),
                ('sacado_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faturaParceiro', to='parceiros.parceiros')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-data_emissao'],
            },
        ),
    ]
