# Generated by Django 5.1.1 on 2024-10-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0002_remove_faturas_numero_fatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faturas',
            name='desconto',
        ),
        migrations.AddField(
            model_name='faturas',
            name='acrescimo_em_porcentagem',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='faturas',
            name='acrescimo_em_reais',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='faturas',
            name='desconto_em_porcentagem',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='faturas',
            name='desconto_em_reais',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
