from comercial.tests.tests_calculaFrete import CalculaFreteTest
from comercial.tests.tests_cotacaoPorPeso import CotacaoPorPesoTest
from comercial.tests.tests_cotacaoPorVolume import CotacaoPorVolumeTest
from comercial.tests.tests_cotacaoPorPercentual import CotacaoPorPercentualTest
from comercial.tests.tests_cotacaoPorFaixa import CotacaoPorFaixaTest


